# Generated by Django 3.2.7 on 2021-12-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20211212_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_name',
        ),
    ]
