# Generated by Django 3.1.2 on 2021-12-14 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20211213_1547'),
        ('teams', '0005_auto_20211213_1522'),
    ]

    operations = [
    ]
