# Generated by Django 3.1.2 on 2021-12-16 09:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_merge_20211214_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.SlugField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='id',
            field=models.SlugField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
