# Generated by Django 3.1.2 on 2021-12-11 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='userename',
            new_name='username',
        ),
    ]
