# Generated by Django 3.1.2 on 2022-01-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_module_module_icon_active'),
        ('authentication', '0003_newuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='no_of_events_registered',
        ),
        migrations.AddField(
            model_name='newuser',
            name='events_registered',
            field=models.ManyToManyField(related_name='competition', to='competitions.Competition'),
        ),
    ]
