# Generated by Django 3.1.2 on 2021-12-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20211218_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='img',
            field=models.ImageField(default='user-default.png', upload_to='image_uploads/userdp/'),
        ),
    ]
