# Generated by Django 3.1.2 on 2022-01-03 09:48

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_module_module_icon_active'),
        ('authentication', '0004_auto_20220103_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='events_registered',
            field=models.ManyToManyField(blank=True, null=True, related_name='competition', to='competitions.Competition'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='fullname',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
