# Generated by Django 3.1.2 on 2021-12-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_newuser_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='img',
            field=models.ImageField(default='image_uploads/userdp/user-default.png', upload_to='image_uploads/userdp/'),
        ),
    ]
