# Generated by Django 3.1.2 on 2022-01-03 09:48

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20220103_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='alternate_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
