# Generated by Django 3.1.2 on 2021-12-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20211222_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='img',
            field=models.ImageField(default='user-default.png', upload_to='image_uploads/userdp/'),
        ),
    ]
