# Generated by Django 3.1.2 on 2021-12-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20211222_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='alcherid',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='interest',
            field=models.CharField(blank=True, choices=[('dance', 'Dance'), ('music', 'Music'), ('stagecraft', 'Stagecraft'), ('fashion', 'Fashion'), ('classapart', 'Class Apart'), ('arttalkies', 'Art Talkies'), ('literacy', 'Literacy'), ('digitaldextirity', 'Digital Dextirity'), ('lightscameraaction', 'Lights Camera Action'), ('informals', 'Informals')], max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='no_of_events_registered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newuser',
            name='team_members',
            field=models.IntegerField(default=0),
        ),
    ]
