# Generated by Django 3.1.2 on 2021-12-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20211224_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='alcherid',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
