# Generated by Django 3.1.2 on 2021-12-24 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20211224_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='alcherid',
        ),
    ]
