# Generated by Django 3.1.2 on 2021-12-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_remove_newuser_alcherid'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='alcherid',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
