# Generated by Django 3.1.2 on 2021-12-25 06:10

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0020_module_module_icon'),
        ('authentication', '0012_newuser_alcherid'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='alternate_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='interest',
        ),
        migrations.AddField(
            model_name='newuser',
            name='interest',
            field=models.ManyToManyField(related_name='interest', to='competitions.Module'),
        ),
    ]
