# Generated by Django 3.1.7 on 2021-12-13 10:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competitions',
            fields=[
                ('id', models.SlugField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('module', models.CharField(choices=[('Dance', 'Dance'), ('Music', 'Music'), ('Stagecraft', 'Stagecraft'), ('Fashion', 'Fashion'), ('Class Appart', 'Class Appart'), ('Art Talkies', 'Art Talkies'), ('Literacy', 'Literacy'), ('Digital Dextirity', 'Digital Dextirity'), ('Lights Camera Action', 'Lights Camera Action'), ('Informals', 'Informals')], max_length=127)),
                ('event_name', models.CharField(max_length=255)),
                ('event_desc', models.CharField(max_length=255)),
                ('members', models.IntegerField(default=1)),
                ('location', models.CharField(max_length=63)),
                ('prize_worth', models.IntegerField()),
                ('image', models.ImageField(default='image-uploads/event_default.png', upload_to='image-uploads/')),
            ],
        ),
    ]
