# Generated by Django 3.1.2 on 2021-12-30 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.SlugField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('event_desc', models.CharField(max_length=255)),
                ('event_rules', models.TextField()),
                ('min_members', models.IntegerField(default=1)),
                ('max_members', models.IntegerField(default=1)),
                ('location', models.CharField(max_length=63)),
                ('prize_worth', models.IntegerField()),
                ('image', models.ImageField(default='event_default.png', upload_to='image_uploads/event_pics/')),
            ],
        ),
        migrations.CreateModel(
            name='CompTeam',
            fields=[
                ('id', models.SlugField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_name1', to='competitions.competition')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_leader', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='compteams', to='teams.TeamMembers')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.SlugField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=127)),
                ('module_query_name_without_spaces_all_small', models.CharField(max_length=127)),
                ('module_icon', models.ImageField(default='module_icon_default.png', upload_to='image_uploads/moduleicons/')),
            ],
        ),
        migrations.CreateModel(
            name='PreviousPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=2000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_name2', to='competitions.competition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compteams2', to='competitions.compteam')),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulename', to='competitions.module'),
        ),
    ]
