# Generated by Django 3.1.2 on 2021-12-16 09:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.SlugField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('module', models.CharField(choices=[('Dance', 'Dance'), ('Music', 'Music'), ('Stagecraft', 'Stagecraft'), ('Fashion', 'Fashion'), ('Class Appart', 'Class Appart'), ('Art Talkies', 'Art Talkies'), ('Literacy', 'Literacy'), ('Digital Dextirity', 'Digital Dextirity'), ('Lights Camera Action', 'Lights Camera Action'), ('Informals', 'Informals')], max_length=127)),
                ('event_name', models.CharField(max_length=255)),
                ('event_desc', models.CharField(max_length=255)),
                ('max_members', models.IntegerField(default=1)),
                ('location', models.CharField(max_length=63)),
                ('prize_worth', models.IntegerField()),
                ('image', models.ImageField(default='event_default.png', upload_to='image_uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='CompTeam',
            fields=[
                ('id', models.SlugField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('teamname', models.CharField(max_length=255, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_particiaptedd', to='competitions.competition')),
                ('members', models.ManyToManyField(related_name='compteams', to='teams.TeamMembers')),
            ],
        ),
    ]
