# Generated by Django 3.1.7 on 2021-12-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='event_rules',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='min_members',
            field=models.IntegerField(default=1),
        ),
    ]
