# Generated by Django 3.1.7 on 2021-12-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitions',
            name='image',
            field=models.ImageField(default='image_uploads/event_default.png', upload_to='image_uploads/'),
        ),
    ]
