# Generated by Django 3.1.2 on 2021-12-30 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_remove_competition_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PreviousPerformance',
            new_name='SubmitPerformance',
        ),
    ]
