# Generated by Django 3.1.7 on 2021-12-13 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_auto_20211213_1614'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Competitions',
            new_name='Competition',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='members',
            new_name='max_members',
        ),
    ]
