# Generated by Django 3.1.2 on 2021-12-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_auto_20211222_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousperformance',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='previousperformance',
            name='link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
