# Generated by Django 3.1.7 on 2021-12-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_auto_20211213_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='image',
            field=models.ImageField(default='event_default.png', upload_to='image_uploads/'),
        ),
    ]
