# Generated by Django 3.1.2 on 2021-12-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_auto_20211230_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_icon_active',
            field=models.ImageField(default='module_icon_default.png', upload_to='image_uploads/moduleicons/active/'),
        ),
    ]
