# Generated by Django 3.1.2 on 2021-12-14 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20211213_1522'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0004_auto_20211213_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('submission_done', models.BooleanField(default=False)),
                ('submission_link', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_particiaptd', to='competitions.competition')),
                ('members', models.ManyToManyField(related_name='compteams', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subteams', to='teams.team')),
            ],
        ),
    ]
