# Generated by Django 3.1.2 on 2021-12-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_auto_20211224_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='event_rules',
            field=models.FileField(blank=True, null=True, upload_to='image_uploads/rulebooks/'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='image',
            field=models.ImageField(default='event_default.png', upload_to='image_uploads/event_pics/'),
        ),
    ]
