# Generated by Django 3.1.2 on 2021-12-14 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_remove_compteam_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compteam',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_particiaptedd', to='competitions.competition'),
        ),
    ]
