# Generated by Django 3.1.2 on 2021-12-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_auto_20211224_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='module',
            field=models.CharField(choices=[('dance', 'Dance'), ('Music', 'Music'), ('Stagecraft', 'Stagecraft'), ('Fashion', 'Fashion'), ('Class Appart', 'Class Appart'), ('Art Talkies', 'Art Talkies'), ('Literacy', 'Literacy'), ('Digital Dextirity', 'Digital Dextirity'), ('Lights Camera Action', 'Lights Camera Action'), ('Informals', 'Informals')], max_length=127),
        ),
    ]
