# Generated by Django 3.1.2 on 2021-12-14 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_auto_20211214_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compteam',
            old_name='title',
            new_name='teamname',
        ),
        migrations.RemoveField(
            model_name='compteam',
            name='description',
        ),
        migrations.RemoveField(
            model_name='compteam',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='compteam',
            name='submission_done',
        ),
        migrations.RemoveField(
            model_name='compteam',
            name='submission_link',
        ),
    ]
