# Generated by Django 3.1.2 on 2021-12-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_auto_20211224_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='module',
            field=models.CharField(choices=[('dance', 'Dance'), ('music', 'Music'), ('stagecraft', 'Stagecraft'), ('fashion', 'Fashion'), ('classapart', 'Class Apart'), ('arttalkies', 'Art Talkies'), ('literacy', 'Literacy'), ('digitaldextirity', 'Digital Dextirity'), ('lightscameraaction', 'Lights Camera Action'), ('informals', 'Informals')], max_length=127),
        ),
    ]
