# Generated by Django 3.1.2 on 2021-12-14 11:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_auto_20211214_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compteam',
            name='id',
            field=models.SlugField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
