# Generated by Django 3.1.2 on 2021-12-25 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_auto_20211225_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='module_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modulename', to='competitions.modules'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='module',
            field=models.CharField(max_length=127),
        ),
    ]
