# Generated by Django 3.1.2 on 2021-12-25 04:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_auto_20211225_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='id',
            field=models.SlugField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
