# Generated by Django 3.1.2 on 2021-12-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0013_competition_module_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='event_rules_pdf',
            field=models.FileField(blank=True, null=True, upload_to='image_uploads/rulebooks/'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='event_rules',
            field=models.TextField(),
        ),
    ]
