# Generated by Django 3.1.2 on 2021-12-25 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0014_auto_20211225_1029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modules',
            new_name='Module',
        ),
    ]
