# Generated by Django 3.1.2 on 2021-12-25 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0017_auto_20211225_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulename', to='competitions.module'),
        ),
    ]
