# Generated by Django 3.1.2 on 2021-12-25 05:12

import competitions.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0018_auto_20211225_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='event_rules_pdf',
            field=models.FileField(blank=True, null=True, upload_to='image_uploads/rulebooks/', validators=[competitions.validators.validate_file_extension]),
        ),
    ]
