# Generated by Django 3.1.2 on 2021-12-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0019_auto_20211225_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_icon',
            field=models.ImageField(default='module_icon_default.png', upload_to='image_uploads/moduleicons/'),
        ),
    ]
