# Generated by Django 3.1.7 on 2021-12-30 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0021_remove_compteam_teamname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='event_rules_pdf',
        ),
    ]
